name: Build

on:
  workflow_call:
    inputs:
      release_version:
        type: string
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install
          
      - name: Build Executable
        run: |
          poetry run pyinstaller --onefile --name er-mailtool src/main.py
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: er-mailtool-linux
          path: dist/er-mailtool

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
